/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


#import <CommCenter/CommCenter-Structs.h>
@class ACAccountStore;

@interface ACAccountStoreDelegate : NSObject {

	ACAccountStore* fAccountStore;
	shared_ptr<const Registry>* fRegistry;
	BOOL fStoreReady;
	BOOL fStoreDidChangeInProcess;
	queue* fQueue;
	block<void ()(iCloudAccountEvent, const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> &)>* fCallback;
	shared_ptr<ctu::Timer>* fRetryEvent;
	basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> fCurrentUsername;
	shared_ptr<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>* fHookup;
	queue* fAccountStoreLongQueue;
	shared_ptr<ctu::Logger>* logger;

}
-(id)initWithCallback:(/*^block*/id)arg1 queue:(queue*)arg2 registry:(const shared_ptr<const Registry>*)arg3 ;
-(void)dealloc;
-(void)initAccountNameWithRetry;
-(void)storeStatusChanged:(id)arg1 ;
-(void)findAccountName:(/*^block*/id)arg1 ;
-(const basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)getPrimaryAccount;
-(BOOL)isManagedAppleId;
@end

