/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:29 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/

#import <CommCenter/CommCenter-Structs.h>
#import <libobjc.A.dylib/NSXPCListenerDelegate.h>
#import <CommCenter/CTCarrierSpaceClientProxyDelegate.h>

@class NSXPCListener, NSMutableArray, NSString;

@interface CarrierSpaceServerImpl : NSObject <NSXPCListenerDelegate, CTCarrierSpaceClientProxyDelegate> {

	NSXPCListener* fXpcListener;
	NSMutableArray* fClients;
	weak_ptr<CarrierSpaceControllerInterface>* fController;
	shared_ptr<Registry>* fRegistry;
	queue* fQueue;
	shared_ptr<ctu::Logger>* logger;
	shared_ptr<carrier_space::EntitlementValidator>* fEntitlementValidator;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithRegistry:(const shared_ptr<Registry>*)arg1 queue:(queue*)arg2 entitlementValidator:(unique_ptr<carrier_space::EntitlementValidator, std::__1::default_delete<carrier_space::EntitlementValidator>>*)arg3 ;
-(void)bootstrapWithListener:(id)arg1 controller:(weak_ptr<CarrierSpaceControllerInterface>*)arg2 ;
-(void)stop;
-(void)capabilitiesChangeNotification:(id)arg1 ;
-(void)userConsentFlowInfoChangeNotification;
-(void)usageInfoChangeNotification;
-(void)plansInfoChangeNotification;
-(void)appsInfoChangeNotification;
-(void)dataPlanMetricsChangeNotification;
-(void)planPurchaseStatusNotification:(unsigned char)arg1 plan:(id)arg2 ;
-(id)_endpoint;
-(BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2 ;
-(void)proxyDidBecomeInvalidated:(id)arg1 ;
@end

