/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:29 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


@class NEPolicyResult;

@interface CCNEPolicyResult : NSObject {

	NEPolicyResult* result;

}
+(id)skipWithOrder:(unsigned)arg1 ;
+(id)drop;
+(id)netAgentUUID:(id)arg1 ;
+(id)scopedNetworkAgent:(id)arg1 ;
-(id)init;
@end

