/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:29 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


@class NEPolicySession;

@interface CCNEPolicySession : NSObject {

	NEPolicySession* session;
	BOOL _dirty;

}

@property (assign,nonatomic) BOOL dirty;              //@synthesize dirty=_dirty - In the implementation block
-(id)init;
-(unsigned long long)addPolicy:(id)arg1 ;
-(BOOL)removePolicyWithID:(unsigned long long)arg1 ;
-(BOOL)apply;
-(BOOL)dirty;
-(void)setDirty:(BOOL)arg1 ;
@end

