/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


@interface CellularPlanUserNotificationDelegate : NSObject
-(void)publishUserNotificationWithBundleIdentifier:(id)arg1 title:(id)arg2 body:(id)arg3 csn:(id)arg4 ;
-(void)publishUserNotificationWithBundleIdentifier:(id)arg1 requestIdentifier:(id)arg2 title:(id)arg3 body:(id)arg4 actionUrl:(id)arg5 ;
-(void)removeNotificationWithBundleIdentifier:(id)arg1 requestIdentifier:(id)arg2 ;
@end

