/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:29 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/

#import <CommCenter/CommCenter-Structs.h>
#import <libobjc.A.dylib/IDSServiceDelegate.h>

@class IDSService, NSString;

@interface CellularPlanIDSServiceDelegate : NSObject <IDSServiceDelegate> {

	IDSService* fIDSService;
	queue* fQueue;
	shared_ptr<const Registry>* fRegistry;
	unique_ptr<ctu::OsLogLogger, std::__1::default_delete<ctu::OsLogLogger>>* logger;
	unsigned char fServiceType;
	map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::pair<void ()(ctu::result<CellularPlanIDSMessage, CellularPlanIDSError>), std::__1::unique_ptr<ctu::Timer, std::__1::default_delete<ctu::Timer>>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::pair<void ()(ctu::result<CellularPlanIDSMessage, CellularPlanIDSError>), std::__1::unique_ptr<ctu::Timer, std::__1::default_delete<ctu::Timer>>>>>>* fResponseHandlers;
	vector<(anonymous namespace)::CellularPlanIDSCallbacks, std::__1::allocator<(anonymous namespace)::CellularPlanIDSCallbacks>>* fCallbacks;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithQueue:(dispatch_queue_sRef)arg1 registry:(const shared_ptr<const Registry>*)arg2 serviceType:(unsigned char)arg3 ;
-(void)startService;
-(BOOL)registerWithName:(id)arg1 supportedIncomingMessageTypes:(bitset<12>)arg2 validateDeviceCallback:(/*^block*/id)arg3 devicesChangedCallback:(/*^block*/id)arg4 incomingMessageCallback:(/*^block*/id)arg5 ;
-(void)dealloc;
-(BOOL)sendMessage:(CellularPlanIDSMessage*)arg1 responseHandler:(/*^block*/id)arg2 ;
-(void)handledResponse:(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>)arg1 ;
-(void)updateTimeoutForTransaction:(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>)arg1 timeout:(int)arg2 ;
-(id)_getDevicesForMessageType:(unsigned short)arg1 ;
-(optional<CellularPlanIDSDevice>=Baligned_storage<CellularPlanIDSDevice>=(dummy_u=[64c]a8)}}Ref)_lookupDevice:(id)arg1 forMessageType:(unsigned short)arg2 ;
-(id)_sendProtobufMessage:(CellularPlanIDSMessage*)arg1 destinations:(id)arg2 ;
-(id)_sendResourceMessage:(CellularPlanIDSMessage*)arg1 destinations:(id)arg2 ;
-(void)_setTimeoutForMessageId:(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>)arg1 responseTimer:(unique_ptr<ctu::Timer, std::__1::default_delete<ctu::Timer>>*)arg2 timeout:(int)arg3 ;
-(void)service:(id)arg1 devicesChanged:(id)arg2 ;
-(void)service:(id)arg1 linkedDevicesChanged:(id)arg2 ;
-(void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(BOOL)arg4 error:(id)arg5 ;
-(void)service:(id)arg1 account:(id)arg2 incomingUnhandledProtobuf:(id)arg3 fromID:(id)arg4 context:(id)arg5 ;
-(void)service:(id)arg1 account:(id)arg2 incomingResourceAtURL:(id)arg3 metadata:(id)arg4 fromID:(id)arg5 context:(id)arg6 ;
-(void)_handleIncomingRequest:(id)arg1 service:(id)arg2 account:(id)arg3 fromID:(id)arg4 context:(id)arg5 ;
-(void)_handleIncomingResponse:(id)arg1 service:(id)arg2 account:(id)arg3 fromID:(id)arg4 context:(id)arg5 ;
-(void)_handleIncomingIndication:(id)arg1 service:(id)arg2 account:(id)arg3 fromID:(id)arg4 context:(id)arg5 ;
@end

