/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


#import <CommCenter/CommCenter-Structs.h>
@class NSString;

@interface CellDataActivationFailureAlertItem : NSObject {

	int _error;
	BOOL _suggestWiFi;
	NSString* _reason;
	dict* _additionalData;
	NSString* _settingsText;
	NSString* _okText;
	NSString* _body;
	NSString* _title;
	shared_ptr<const Registry>* fRegistry;
	const OsLogLogger* fLogger;

}
-(id)initWithErrorCode:(int)arg1 reason:(id)arg2 additionalData:(dict*)arg3 suggestWiFi:(BOOL)arg4 registry:(shared_ptr<const Registry>*)arg5 logger:(const OsLogLogger*)arg6 ;
-(void)dealloc;
-(void)button_config:(BOOL)arg1 ;
-(void)show;
@end

