/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


#import <CommCenter/CommCenter-Structs.h>
@class NSLock;

@interface CellDataActivationFailureAlertState : NSObject {

	NSLock* fLockMain;
	int fAction;
	CFSharedRef<const __CFData>* fDataPlanCsn;
	CFSharedRef<const __CFString>* fDataPlanUrl;
	CFSharedRef<const __CFString>* fDataPlanIccid;
	BOOL _scheduled;

}

@property (assign) BOOL scheduled;              //@synthesize scheduled=_scheduled - In the implementation block
@property (assign) int action; 
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)appInit;
-(BOOL)trylockMain;
-(void)unlockMain;
-(void)lockScheduled;
-(void)unlockScheduled;
-(int)action;
-(void)setAction:(int)arg1 ;
-(void)setDataPlanCsn:(CFSharedRef<const __CFData>*)arg1 ;
-(void)setDataPlanUrl:(CFSharedRef<const __CFString>*)arg1 ;
-(void)setDataPlanIccid:(CFSharedRef<const __CFString>*)arg1 ;
-(void)handleActionResponse;
-(BOOL)scheduled;
-(void)setScheduled:(BOOL)arg1 ;
@end

