/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:29 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/

#import <CommCenter/CommCenter-Structs.h>
#import <libCommCenterBase.dylib/OCSharedLoggable.h>

@class CKContainer;

@interface CKContainerDelegate : OCSharedLoggable {

	CKContainer* fContainer;
	shared_ptr<CellularPlanSettings>* fSettings;
	queue* fQueue;
	function<void (bool)>* fCallback;

}
-(id)initWithQueue:(const queue*)arg1 settings:(const shared_ptr<CellularPlanSettings>*)arg2 callback:(function<void (bool)>*)arg3 ;
-(void)_cloudKitAccountStatusChanged:(id)arg1 ;
-(void)dealloc;
@end

