/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:29 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


@protocol CTCarrierSpaceServiceInterface <NSObject>
@required
-(void)getAuthenticationContext:(/*^block*/id)arg1;
-(void)ping:(/*^block*/id)arg1;
-(void)fetchPlansInfo:(BOOL)arg1 completion:(/*^block*/id)arg2;
-(void)getCapabilities:(/*^block*/id)arg1;
-(void)fetchAppsInfo:(BOOL)arg1 completion:(/*^block*/id)arg2;
-(void)fetchUsageInfo:(BOOL)arg1 completion:(/*^block*/id)arg2;
-(void)refreshAllInfo:(/*^block*/id)arg1;
-(void)refreshAppsInfo:(/*^block*/id)arg1;
-(void)setUserConsent:(BOOL)arg1 completion:(/*^block*/id)arg2;
-(void)getUserConsentFlowInfo:(/*^block*/id)arg1;
-(void)fetchDataPlanMetrics:(/*^block*/id)arg1;
-(void)setUserInAuthFlow:(BOOL)arg1 completion:(/*^block*/id)arg2;
-(void)userDidAcceptPlanTerms:(BOOL)arg1 completion:(/*^block*/id)arg2;
-(void)refreshPlansInfo:(/*^block*/id)arg1;
-(void)refreshUsageInfo:(/*^block*/id)arg1;
-(void)authenticationDidComplete:(id)arg1 completion:(/*^block*/id)arg2;
-(void)authenticationDidFail:(id)arg1 completion:(/*^block*/id)arg2;
-(void)purchasePlan:(id)arg1 authInfo:(id)arg2 completion:(/*^block*/id)arg3;
-(void)testMode:(BOOL)arg1 config:(id)arg2 completion:(/*^block*/id)arg3;

@end

