/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:29 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/

#import <CommCenter/CommCenter-Structs.h>
#import <libobjc.A.dylib/NSXPCConnectionDelegate.h>
#import <libobjc.A.dylib/CTCarrierSpaceServiceInterface.h>

@protocol CTCarrierSpaceClientProxyDelegate;
@class NSXPCConnection, NSString;

@interface CTCarrierSpaceClientProxy : NSObject <NSXPCConnectionDelegate, CTCarrierSpaceServiceInterface> {

	shared_ptr<Registry>* fRegistry;
	weak_ptr<CarrierSpaceControllerInterface>* fWeakController;
	queue* fQueue;
	basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> fProcessName;
	shared_ptr<ctu::Logger>* logger;
	BOOL fIsInAuthFlow;
	NSXPCConnection* _connection;
	id<CTCarrierSpaceClientProxyDelegate> _delegate;
	shared_ptr<carrier_space::EntitlementValidator>* fEntitlementValidator;

}

@property (assign,nonatomic) NSXPCConnection * connection;                                                       //@synthesize connection=_connection - In the implementation block
@property (assign,nonatomic) shared_ptr<carrier_space::EntitlementValidator>* entitlementValidator; 
@property (assign,nonatomic,__weak) id<CTCarrierSpaceClientProxyDelegate> delegate;                              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithConnection:(id)arg1 registry:(shared_ptr<Registry>*)arg2 controller:(weak_ptr<CarrierSpaceControllerInterface>*)arg3 logger:(shared_ptr<ctu::Logger>*)arg4 ;
-(void)_handleConnectionInvalidated;
-(BOOL)_isEntitledForControl;
-(id)_processNameWithPid;
-(void)connection:(id)arg1 handleInvocation:(id)arg2 isReply:(BOOL)arg3 ;
-(void)getCapabilities:(/*^block*/id)arg1 ;
-(void)getUserConsentFlowInfo:(/*^block*/id)arg1 ;
-(void)setUserConsent:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)fetchUsageInfo:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)fetchPlansInfo:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)fetchAppsInfo:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)refreshAllInfo:(/*^block*/id)arg1 ;
-(void)purchasePlan:(id)arg1 authInfo:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)fetchDataPlanMetrics:(/*^block*/id)arg1 ;
-(void)ping:(/*^block*/id)arg1 ;
-(void)testMode:(BOOL)arg1 config:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)setUserInAuthFlow:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)authenticationDidComplete:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)authenticationDidFail:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)userDidAcceptPlanTerms:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)refreshUsageInfo:(/*^block*/id)arg1 ;
-(void)refreshPlansInfo:(/*^block*/id)arg1 ;
-(void)refreshAppsInfo:(/*^block*/id)arg1 ;
-(void)getAuthenticationContext:(/*^block*/id)arg1 ;
-(void)sendIfRespondsTo:(SEL)arg1 handler:(/*^block*/id)arg2 ;
-(void)notifyCapabilitiesChanged:(id)arg1 ;
-(void)notifyUserConsentFlowInfoChanged;
-(void)notifyUsageChanged;
-(void)notifyPlansChanged;
-(void)notifyAppsChanged;
-(void)notifyDataPlanMetricsChanged;
-(void)notifyPlanPurchaseStatusChanged:(id)arg1 status:(unsigned char)arg2 ;
-(shared_ptr<carrier_space::EntitlementValidator>*)entitlementValidator;
-(void)setEntitlementValidator:(shared_ptr<carrier_space::EntitlementValidator>*)arg1 ;
-(NSXPCConnection *)connection;
-(void)setConnection:(NSXPCConnection *)arg1 ;
-(id<CTCarrierSpaceClientProxyDelegate>)delegate;
-(void)setDelegate:(id<CTCarrierSpaceClientProxyDelegate>)arg1 ;
@end

