/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:29 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/

#import <CommCenter/CommCenter-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSString;

@interface CTCellularPlanManagerCameraScanAction : NSObject <NSCopying, NSSecureCoding> {

	NSString* _title;
	NSString* _message;
	NSString* _smdpAddress;
	NSString* _matchingId;
	NSString* _OID;

}

@property (nonatomic,retain) NSString * smdpAddress;              //@synthesize smdpAddress=_smdpAddress - In the implementation block
@property (nonatomic,retain) NSString * matchingId;               //@synthesize matchingId=_matchingId - In the implementation block
@property (nonatomic,retain) NSString * OID;                      //@synthesize OID=_OID - In the implementation block
@property (nonatomic,copy) NSString * title;                      //@synthesize title=_title - In the implementation block
@property (nonatomic,copy) NSString * message;                    //@synthesize message=_message - In the implementation block
+(BOOL)supportsSecureCoding;
-(NSString *)smdpAddress;
-(NSString *)matchingId;
-(void)setSmdpAddress:(NSString *)arg1 ;
-(void)setMatchingId:(NSString *)arg1 ;
-(void)performWithCompletionHandler:(/*^block*/id)arg1 ;
-(NSString *)OID;
-(void)setOID:(NSString *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(void)setMessage:(NSString *)arg1 ;
-(NSString *)title;
-(NSString *)message;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)description;
@end

