/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


#import <CommCenter/CommCenter-Structs.h>
@interface CTCellularPlanSettings : NSObject
+(void)performSetupWithRegistry:(const shared_ptr<const Registry>*)arg1 ;
+(id)_bootstrapConnectionProperties;
+(void)_mergeSettingsFromDictionary:(id)arg1 withBootstrap:(id)arg2 internet:(id)arg3 requestUrls:(id)arg4 ;
+(void)cellularPlanRequestSettingsForBootstrap:(id*)arg1 internet:(id*)arg2 requestUrls:(id*)arg3 registry:(const shared_ptr<const Registry>*)arg4 ;
@end

