/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:29 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


#import <CommCenter/CommCenter-Structs.h>
@class CTDeviceDataUsage, NSMutableDictionary;

@interface CTDataUsageBuilder : NSObject {

	shared_ptr<const Registry>* fRegistry;
	const OsLogLogger* fLogger;
	BOOL fIsGreenTea;
	CTDeviceDataUsage* _deviceUsage;
	NSMutableDictionary* _appProperties;

}

@property (nonatomic,retain) CTDeviceDataUsage * deviceUsage;              //@synthesize deviceUsage=_deviceUsage - In the implementation block
@property (retain) NSMutableDictionary * appProperties;                    //@synthesize appProperties=_appProperties - In the implementation block
-(id)initWithPeriods:(unsigned long long)arg1 andRegistry:(const shared_ptr<const Registry>*)arg2 andLogger:(const OsLogLogger*)arg3 ;
-(BOOL)addUsage:(id)arg1 forBundle:(id)arg2 forPeriod:(unsigned long long)arg3 ;
-(CTDeviceDataUsage *)deviceUsage;
-(void)setDeviceUsage:(CTDeviceDataUsage *)arg1 ;
-(NSMutableDictionary *)appProperties;
-(void)setAppProperties:(NSMutableDictionary *)arg1 ;
@end

