/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/

#import <CommCenter/CommCenter-Structs.h>
#import <libobjc.A.dylib/APSConnectionDelegate.h>

@class APSConnection, NSArray, NSString;

@interface CTPushManager : NSObject <APSConnectionDelegate> {

	APSConnection* _connection;
	NSArray* _currentTopics;
	NSString* _environment;
	dispatch_queue_sRef _queue;
	weak_ptr<push::PushController>* _controller;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithPushController:(shared_ptr<push::PushController>*)arg1 andQueue:(dispatch_queue_sRef)arg2 ;
-(void)dealloc;
-(void)_connect;
-(void)_disconnect;
-(void)startConnection;
-(void)_setEnabledTopics_sync:(id)arg1 ;
-(void)_reconnect;
-(void)setEnabledTopics:(CFArrayRef)arg1 ;
-(void)useDevelopmentEnvironment:(BOOL)arg1 ;
-(void)connection:(id)arg1 didReceivePublicToken:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveToken:(id)arg2 forTopic:(id)arg3 identifier:(id)arg4 ;
-(void)connection:(id)arg1 didReceiveIncomingMessage:(id)arg2 ;
@end

