/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:29 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/

#import <CommCenter/CommCenter-Structs.h>
#import <libobjc.A.dylib/CLLocationManagerDelegate.h>

@class CLLocationManager, CLLocation, CLAssertion, NSString;

@interface CTWifiLocationManager : NSObject <CLLocationManagerDelegate> {

	CLLocationManager* _manager;
	CLLocation* _location;
	BOOL _locationRequested;
	BOOL _locationAvailable;
	BOOL _locationServiceDenied;
	BOOL _locationServiceAuthorized;
	BOOL _initialized;
	queue* _queue;
	unique_ptr<ctu::OsLogLogger, std::__1::default_delete<ctu::OsLogLogger>>* logger;
	BOOL _forceLocationLookup;
	unsigned _desiredIntegrity;
	CLAssertion* locationServicesAssertion;
	double _desiredLocationAccuracy;

}

@property (copy) CLLocation * location;                                            //@synthesize location=_location - In the implementation block
@property (assign,nonatomic) BOOL forceLocationLookup;                             //@synthesize forceLocationLookup=_forceLocationLookup - In the implementation block
@property (assign,nonatomic) BOOL locationRequested;                               //@synthesize locationRequested=_locationRequested - In the implementation block
@property (assign,nonatomic) BOOL locationAvailable;                               //@synthesize locationAvailable=_locationAvailable - In the implementation block
@property (assign) double desiredLocationAccuracy;                                 //@synthesize desiredLocationAccuracy=_desiredLocationAccuracy - In the implementation block
@property (assign) unsigned desiredIntegrity;                                      //@synthesize desiredIntegrity=_desiredIntegrity - In the implementation block
@property (nonatomic,retain) CLAssertion * locationServicesAssertion; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)dealloc;
-(void)initialize;
-(void)disableVoWiFiLocationStatusOnFirstLaunch;
-(void)handleDataMigration;
-(void)configureLocationManagerWithForceLocationLookup:(BOOL)arg1 ;
-(BOOL)isLocationAcceptable:(double)arg1 integrity:(unsigned)arg2 accuracy:(double)arg3 ;
-(void)shouldUpdateLocation:(BOOL)arg1 forceLocationLookup:(BOOL)arg2 ;
-(void)startLocationUpdateWithForceLocationLookup:(BOOL)arg1 ;
-(void)stopLocationUpdates;
-(BOOL)isLocationServiceEnabled;
-(id)copyLastKnownLocation;
-(BOOL)isLocationServiceDenied;
-(BOOL)isLocationServiceAuthorized;
-(void)registerWifiCallingEntity;
-(void)enableVoWiFiLocationStatus:(BOOL)arg1 ;
-(void)handleDumpState;
-(void)locationManager:(id)arg1 didUpdateLocations:(id)arg2 ;
-(void)locationManager:(id)arg1 didFailWithError:(id)arg2 ;
-(void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2 ;
-(CLLocation *)location;
-(void)setLocation:(CLLocation *)arg1 ;
-(BOOL)locationRequested;
-(void)setLocationRequested:(BOOL)arg1 ;
-(CLAssertion *)locationServicesAssertion;
-(void)setLocationServicesAssertion:(CLAssertion *)arg1 ;
-(BOOL)forceLocationLookup;
-(void)setForceLocationLookup:(BOOL)arg1 ;
-(BOOL)locationAvailable;
-(void)setLocationAvailable:(BOOL)arg1 ;
-(double)desiredLocationAccuracy;
-(void)setDesiredLocationAccuracy:(double)arg1 ;
-(unsigned)desiredIntegrity;
-(void)setDesiredIntegrity:(unsigned)arg1 ;
@end

