/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


@interface CTXPCSlotIDPlaceholder : NSObject {

	int _slot;

}

@property (assign,nonatomic) int slot;              //@synthesize slot=_slot - In the implementation block
-(id)initWithSlot:(int)arg1 ;
-(int)slot;
-(void)setSlot:(int)arg1 ;
@end

