/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:29 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/

#import <CommCenter/CommCenter-Structs.h>
#import <CommCenter/CTXPCClientHandler.h>
#import <CommCenter/CTXPCClientProxyInterface.h>
#import <libobjc.A.dylib/CTXPCServiceInterface.h>

@class NSXPCInterface, NSString;

@interface CTXPCClientProxy : CTXPCClientHandler <CTXPCClientProxyInterface, CTXPCServiceInterface>

@property (nonatomic,readonly) NSXPCInterface * exportedInterface; 
@property (nonatomic,readonly) NSXPCInterface * remoteInterface; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithRegistry:(const shared_ptr<const Registry>Ref)arg1 queue:(queue*)arg2 connection:(id)arg3 ;
-(NSXPCInterface *)exportedInterface;
-(NSXPCInterface *)remoteInterface;
@end

