/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


@protocol CTXPCServiceCapabilitiesInterface
@required
-(void)context:(id)arg1 recheckPhoneServicesAccountStatus:(id)arg2 completion:(/*^block*/id)arg3;
-(void)context:(id)arg1 setCapability:(id)arg2 enabled:(BOOL)arg3 info:(id)arg4 completion:(/*^block*/id)arg5;
-(void)wifiCallingCTFollowUpComplete:(id)arg1 withCompletion:(/*^block*/id)arg2;
-(void)context:(id)arg1 mandatoryDisableVoLTE:(BOOL)arg2 withCompletion:(/*^block*/id)arg3;
-(void)getSupports5G:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getPhoneServicesDeviceList:(/*^block*/id)arg1;
-(void)context:(id)arg1 getCapability:(id)arg2 completion:(/*^block*/id)arg3;
-(void)context:(id)arg1 canSetCapability:(id)arg2 completion:(/*^block*/id)arg3;
-(void)context:(id)arg1 removePhoneServicesDevice:(id)arg2 withCompletion:(/*^block*/id)arg3;
-(void)context:(id)arg1 isMandatoryDisabledVoLTE:(/*^block*/id)arg2;
-(void)context:(id)arg1 getSystemCapabilities:(/*^block*/id)arg2;
-(void)context:(id)arg1 addPhoneServicesDevice:(id)arg2 withCompletion:(/*^block*/id)arg3;
-(void)getPhoneServicesDeviceInfo:(/*^block*/id)arg1;

@end

