/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/

#import <CommCenter/CommCenter-Structs.h>
#import <libCommCenterBase.dylib/OCSharedLoggable.h>
#import <libobjc.A.dylib/NSXPCListenerDelegate.h>

@protocol CTXPCListenerDelegate;
@class NSXPCListener, NSXPCListenerEndpoint, NSString;

@interface CTXPCListener : OCSharedLoggable <NSXPCListenerDelegate> {

	shared_ptr<ctu::Logger>* logger;
	id<CTXPCListenerDelegate> _delegate;
	NSXPCListener* _listener;
	const char* _name;
	NSXPCListenerEndpoint* _endpoint;

}

@property (nonatomic,retain) NSXPCListener * listener;                               //@synthesize listener=_listener - In the implementation block
@property (assign,nonatomic) const char* name;                                       //@synthesize name=_name - In the implementation block
@property (nonatomic,retain) NSXPCListenerEndpoint * endpoint;                       //@synthesize endpoint=_endpoint - In the implementation block
@property (assign,nonatomic,__weak) id<CTXPCListenerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithListener:(id)arg1 queue:(queue*)arg2 name:(const char*)arg3 logContext:(OsLogContext*)arg4 ;
-(void)bootstrapWithDelegate:(id)arg1 ;
-(void)start;
-(void)stop;
-(NSXPCListenerEndpoint *)endpoint;
-(BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2 ;
-(id<CTXPCListenerDelegate>)delegate;
-(void)setDelegate:(id<CTXPCListenerDelegate>)arg1 ;
-(NSXPCListener *)listener;
-(void)setListener:(NSXPCListener *)arg1 ;
-(const char*)name;
-(void)setName:(const char*)arg1 ;
-(void)setEndpoint:(NSXPCListenerEndpoint *)arg1 ;
@end

