/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


@protocol CTXPCServiceDataInterface
@required
-(void)getCurrentDataSubscriptionContext:(/*^block*/id)arg1;
-(void)enterLoopBackMode:(/*^block*/id)arg1;
-(void)getDataStatus:(id)arg1 completion:(/*^block*/id)arg2;
-(void)sendDeadPeerDetection:(/*^block*/id)arg1;
-(void)getPreferredDataSubscriptionContext:(/*^block*/id)arg1;
-(void)getActiveConnections:(id)arg1 completion:(/*^block*/id)arg2;
-(void)resetAPNSettings:(/*^block*/id)arg1;
-(void)setSupportDynamicDataSimSwitch:(BOOL)arg1 forIccid:(id)arg2 completion:(/*^block*/id)arg3;
-(void)getTetheringStatus:(/*^block*/id)arg1;
-(void)setInternationalDataAccess:(id)arg1 status:(BOOL)arg2 completion:(/*^block*/id)arg3;
-(void)getConnectionState:(id)arg1 connectionType:(int)arg2 completion:(/*^block*/id)arg3;
-(void)getInternationalDataAccess:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getConnectionAvailability:(id)arg1 connectionType:(int)arg2 completion:(/*^block*/id)arg3;
-(void)getPreferredDataServiceDescriptor:(/*^block*/id)arg1;
-(void)setPacketContextActiveByServiceType:(id)arg1 connectionType:(int)arg2 active:(BOOL)arg3 completion:(/*^block*/id)arg4;
-(void)isTetheringEditingSupported:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getPacketContextCount:(/*^block*/id)arg1;
-(void)getCurrentDataServiceDescriptor:(/*^block*/id)arg1;
-(void)getSupportDynamicDataSimSwitch:(/*^block*/id)arg1;
-(void)setSupportDynamicDataSimSwitch:(BOOL)arg1 completion:(/*^block*/id)arg2;
-(void)getNATTKeepAliveOverCell:(id)arg1 completion:(/*^block*/id)arg2;

@end

