/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


@protocol CTXPCServiceRegistrationInterface
@required
-(void)copyRejectCauseCode:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyOperatorName:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getSignalStrengthMeasurementsAsync:(id)arg1 completion:(/*^block*/id)arg2;
-(void)setSupports5GStandalone:(id)arg1 enabled:(BOOL)arg2 completion:(/*^block*/id)arg3;
-(void)copyIsInHomeCountry:(id)arg1 completion:(/*^block*/id)arg2;
-(void)setActiveBandInfo:(id)arg1 bands:(id)arg2 completion:(/*^block*/id)arg3;
-(void)getSupports5GStandalone:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getPublicSignalStrength:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyMobileNetworkCode:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyNetworkSelectionState:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getCurrentRat:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyBandInfo:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyNetworkList:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getRatSelectionMask:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getEncryptionStatus:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getNRDisableStatus:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getIMSRegistrationStatus:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyLocalizedOperatorName:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getBandInfo:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getDataMode:(id)arg1 completion:(/*^block*/id)arg2;
-(void)selectNetwork:(id)arg1 network:(id)arg2 completion:(/*^block*/id)arg3;
-(void)getSupportedDataRates:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyNetworkSelectionInfo:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyWirelessTechnology:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyServingPlmn:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyRadioAccessTechnology:(id)arg1 completion:(/*^block*/id)arg2;
-(void)fetchNetworkList:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getSignalStrengthMeasurements:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyAbbreviatedOperatorName:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyRegistrationIMSTransportInfo:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyRegistrationDisplayStatus:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyRegistrationAgentStatus:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyNetworkSelection:(id)arg1 completion:(/*^block*/id)arg2;
-(void)setRatSelection:(id)arg1 selection:(id)arg2 preferred:(id)arg3 completion:(/*^block*/id)arg4;
-(void)setMaxDataRate:(id)arg1 rate:(long long)arg2 completion:(/*^block*/id)arg3;
-(void)copyLastKnownMobileCountryCode:(id)arg1 completion:(/*^block*/id)arg2;
-(void)automaticallySelectNetwork:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getVoiceLinkQualityMetric:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyRegistrationStatus:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getRatSelection:(id)arg1 completion:(/*^block*/id)arg2;
-(void)isNetworkReselectionNeeded:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getMaxDataRate:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getEnhancedVoiceLinkQualityMetric:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyNetworkSelectionMode:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyMobileCountryCode:(id)arg1 completion:(/*^block*/id)arg2;
-(void)isNetworkSelectionMenuAvailable:(id)arg1 completion:(/*^block*/id)arg2;
-(void)setBandInfo:(id)arg1 bands:(id)arg2 completion:(/*^block*/id)arg3;
-(void)getSignalStrengthInfo:(id)arg1 completion:(/*^block*/id)arg2;
-(void)copyIsDataAttached:(id)arg1 completion:(/*^block*/id)arg2;

@end

