/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/

#import <CommCenter/CommCenter-Structs.h>
#import <Foundation/NSProxy.h>
#import <CommCenter/CoreTelephonyClientDelegateProxyInterface.h>

@protocol CTXPCNotificationSinkInterface, CTXPCDataProviderInterface;
@class Protocol, NSString;

@interface CTXPCNotificationProxy : NSProxy <CoreTelephonyClientDelegateProxyInterface> {

	id<CTXPCNotificationSinkInterface> _sinkDelegate;
	id<CTXPCDataProviderInterface> _dataProviderDelegate;
	queue* _queue;
	Protocol* _protocol;
	shared_ptr<const Registry>* _registry;

}

@property (assign,nonatomic) shared_ptr<const Registry>* registry;                                    //@synthesize registry=_registry - In the implementation block
@property (assign,nonatomic) queue* queue;                                                            //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) Protocol * protocol;                                                     //@synthesize protocol=_protocol - In the implementation block
@property (assign,nonatomic,__weak) id<CTXPCNotificationSinkInterface> sinkDelegate;                  //@synthesize sinkDelegate=_sinkDelegate - In the implementation block
@property (assign,nonatomic,__weak) id<CTXPCDataProviderInterface> dataProviderDelegate;              //@synthesize dataProviderDelegate=_dataProviderDelegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithRegistry:(const shared_ptr<const Registry>*)arg1 queue:(queue*)arg2 ;
-(id)_contextForSlotIDPlaceholder_sync:(id)arg1 ;
-(id)_contextForUUIDPlaceholder_sync:(id)arg1 ;
-(BOOL)_resolvePlaceholders_sync:(id)arg1 ;
-(void)forwardInvocation:(id)arg1 ;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(id<CTXPCNotificationSinkInterface>)sinkDelegate;
-(void)setSinkDelegate:(id<CTXPCNotificationSinkInterface>)arg1 ;
-(id<CTXPCDataProviderInterface>)dataProviderDelegate;
-(void)setDataProviderDelegate:(id<CTXPCDataProviderInterface>)arg1 ;
-(shared_ptr<const Registry>*)registry;
-(void)setRegistry:(shared_ptr<const Registry>*)arg1 ;
-(queue*)queue;
-(void)setQueue:(queue*)arg1 ;
-(Protocol *)protocol;
-(void)setProtocol:(Protocol *)arg1 ;
@end

