/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


@protocol CTXPCServiceSIMToolkitInterface
@required
-(void)sendSIMToolkitStringResponseForContext:(id)arg1 session:(id)arg2 response:(id)arg3 string:(id)arg4 completion:(/*^block*/id)arg5;
-(void)sendSIMToolkitBooleanResponseForContext:(id)arg1 session:(id)arg2 response:(id)arg3 yesNo:(BOOL)arg4 completion:(/*^block*/id)arg5;
-(void)selectSIMToolkitListItemForContext:(id)arg1 session:(id)arg2 response:(id)arg3 index:(id)arg4 completion:(/*^block*/id)arg5;
-(void)cancelSIMToolkitUSSDSessionForContext:(id)arg1 completion:(/*^block*/id)arg2;
-(void)sendSIMToolkitResponseForContext:(id)arg1 session:(id)arg2 response:(id)arg3 completion:(/*^block*/id)arg4;
-(void)sendSIMToolkitUserActivityForContext:(id)arg1 completion:(/*^block*/id)arg2;
-(void)sendSIMToolkitDisplayReadyForContext:(id)arg1 completion:(/*^block*/id)arg2;
-(void)selectSIMToolkitMenuItemForContext:(id)arg1 index:(id)arg2 completion:(/*^block*/id)arg3;
-(void)getSIMToolkitListItemsForContext:(id)arg1 completion:(/*^block*/id)arg2;
-(void)sendSIMToolkitUSSDResponseForContext:(id)arg1 response:(id)arg2 completion:(/*^block*/id)arg3;
-(void)getSIMToolkitMenuForContext:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getSIMToolkitUSSDStringForContext:(id)arg1 completion:(/*^block*/id)arg2;

@end

