/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


@protocol CTXPCServiceCellularUsagePolicyInterface
@required
-(void)interfaceCostExpensive:(id)arg1 completion:(/*^block*/id)arg2;
-(void)isSmartDataModeSupportedWithCompletion:(/*^block*/id)arg1;
-(void)setInterfaceCost:(id)arg1 expensive:(BOOL)arg2 completion:(/*^block*/id)arg3;
-(void)setReliableNetworkFallback:(id)arg1 enable:(BOOL)arg2 completion:(/*^block*/id)arg3;
-(void)reliableNetworkFallback:(id)arg1 completion:(/*^block*/id)arg2;
-(void)setSmartDataMode:(id)arg1 enable:(BOOL)arg2 completion:(/*^block*/id)arg3;
-(void)isHighDataModeSupported:(id)arg1 completion:(/*^block*/id)arg2;
-(void)setLowDataMode:(id)arg1 enable:(BOOL)arg2 completion:(/*^block*/id)arg3;
-(void)smartDataMode:(id)arg1 completion:(/*^block*/id)arg2;
-(void)lowDataMode:(id)arg1 completion:(/*^block*/id)arg2;

@end

