/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


@protocol CTXPCServiceCarrierServicesInterface
@required
-(void)purchaseSweetgumPlan:(id)arg1 completion:(/*^block*/id)arg2;
-(void)refreshSweetgumPlans:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getSweetgumUserConsentInfo:(id)arg1 completion:(/*^block*/id)arg2;
-(void)refreshSweetgumApps:(id)arg1 completion:(/*^block*/id)arg2;
-(void)refreshSweetgumUsage:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getSweetgumDataPlanMetrics:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getSweetgumPlans:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getSweetgumApps:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getSweetgumCapabilities:(id)arg1 completion:(/*^block*/id)arg2;
-(void)getSweetgumUsage:(id)arg1 completion:(/*^block*/id)arg2;
-(void)refreshSweetgumAll:(id)arg1 completion:(/*^block*/id)arg2;
-(void)setSweetgumUserConsent:(id)arg1 userConsent:(BOOL)arg2 completion:(/*^block*/id)arg3;

@end

