/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:29 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


@protocol CXProviderDelegatePrivate <CXProviderDelegate>
@optional
-(void)provider:(id)arg1 performSendMMIOrUSSDCodeAction:(id)arg2;
-(void)provider:(id)arg1 performJoinCallAction:(id)arg2;
-(void)provider:(id)arg1 performSetTTYTypeCallAction:(id)arg2;
-(void)provider:(id)arg1 performSetSendingVideoCallAction:(id)arg2;
-(void)provider:(id)arg1 performSetRelayingCallAction:(id)arg2;
-(void)provider:(id)arg1 performPullCallAction:(id)arg2;
-(void)provider:(id)arg1 performSetVideoPresentationSizeCallAction:(id)arg2;
-(void)provider:(id)arg1 performSetVideoPresentationStateCallAction:(id)arg2;

@end

