/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:29 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/

#import <CommCenter/CommCenter-Structs.h>
#import <libobjc.A.dylib/SBSRemoteAlertHandleObserver.h>

@class SBSRemoteAlertHandle, NSString;

@interface DataActivationLaunchHelper : NSObject <SBSRemoteAlertHandleObserver> {

	SBSRemoteAlertHandle* fAlertHandle;
	LoggerBase<std::__1::shared_ptr<ctu::LogServer>>* fLogger;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithLogger:(LoggerBase<std::__1::shared_ptr<ctu::LogServer>>*)arg1 ;
-(void)launchWithUrl:(id)arg1 options:(id)arg2 ;
-(void)launchWithServiceName:(id)arg1 viewControllerClassName:(id)arg2 options:(id)arg3 ;
-(BOOL)isAlertHandleExistAndValid;
-(void)reactivateDataActivationIfPresent;
-(void)invalidateRemoteAlertHandle;
-(void)remoteAlertHandle:(id)arg1 didInvalidateWithError:(id)arg2 ;
@end

