/*
*This header is generated by classdump-dyld 1.5
*on Tuesday, June 8, 2021 at 2:19:30 PM Central Daylight Time
*Operating System: Version 14.7 (Build 18G5023c)
*Image Source: /System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter
*classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
*/


#import <CommCenter/CommCenter-Structs.h>
@class NWPathEvaluator;

@interface DataConnectionAgentInterfaceObserver : NSObject {

	NWPathEvaluator* fPathEvaluator;
	NWPathEvaluator* fAgentEvaluator;
	DataConnectionAgentPathSatisfactionObserver* fPathSatisfactionObserver;
	basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> fDomain;
	basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> fAgentType;
	Class fAgentClass;
	BOOL fPathAvailable;
	BOOL fAgentAvailable;
	basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> fUuid;
	queue* fQueue;
	shared_ptr<ctu::Logger>* fLogger;

}
-(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>)agentType;
-(id)initWithPathSatisfactionObserver:(DataConnectionAgentPathSatisfactionObserver*)arg1 domain:(id)arg2 agentType:(id)arg3 agentClass:(Class)arg4 logName:(const char*)arg5 uuid:(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>)arg6 queue:(const queue*)arg7 registry:(shared_ptr<const Registry>*)arg8 ;
-(void)doUpdateUUID:(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>)arg1 ;
-(void)doUpdateInterface:(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>)arg1 plainParameters:(id)arg2 domainParameters:(id)arg3 ;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
@end

